name: Update README

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install script dependencies
      run: |-
        gem install feedjira
    - name: Update README.md file
      run: |-
        ruby update_readme.rb
    - name: Commit and push README.md
      run: |-
        git config --global user.email "karreiro@gmail.com"
        git config --global user.name "Guilherme Carreiro"
        git diff --quiet || (git add README.md && git commit -m "Update README.md (`date`)")
        git push -f
